### ISSUE TITLE
Interfacing with sd card via ili9341 display

### ISSUE THREAD

**Issue by cosparks** [supermileage/dynamometer-firmware#11]
- ~~Add connection to ili9341 display with SPI or SPI1 for the pi (using chip select, you can have multiple devices on the same bus).~~
- ~~Find library for reading and writing sd cards (Arduino SD should work)~~
- ~~Find appropriate library for handling csv files (it might also be trivial to come up with your own code).~~

**Comment by cosparks** [comment]
Related to #13

**Comment by cosparks** [comment]
this work should branch from and eventually be merged into dev_pico

**Comment by cosparks** [comment]
@underscoreHasan I'd also like to get an idea of performance: how long does it take to write a 1000 character string?  How long does it take to write a single column entry for a csv file?

Because we're going to have to potentially capture fairly high-resolution data for these csv tables we're building, I'd like to know whether or not we should be tasking the second core on the pico with some of this read/write stuff

**Comment by underscoreHasan** [comment]
Noted, I'll implement time readings when I start working on the .csv writing logic again

**Comment by cosparks** [comment]
@underscoreHasan bumping this issue.  If you're not sure how to go about doing this, then let me know.  Knowing how much processor time it takes to write to the sd card will inform how we should split work between the pico's two cores.

**Comment by cosparks** [comment]
@LaPommeCosmique the comment I made above is still relevant too.  It would be nice to have some data on how long it takes to write small/big chunks of data to the SD card.

**Comment by cosparks** [comment]
Closing this and opening new issue for sd performance testing
