### ISSUE TITLE
IO: Add BPM Control Class

### ISSUE THREAD

**Issue by cosparks** [supermileage/dynamometer-firmware#49]
There are multiple application states which will require the ability to control the BPM control voltage signal, so we need a class which encapsulates this behaviour.  Class should include:
- constructor which takes a pin number (type ```pin_size_t```)
- ```init``` or ```begin``` method which initializes pin
- method: ```setControlSignal(int32_t val)``` where val is a number from 0 to _N_
- method: ```setActive(bool val)``` which turns the module on / off

Things to consider about _N_:
- _N_ is the analog write range on the pico, which needs to be set globally by calling ```analogWriteRange``` in ```setup```
- we also need to set the analog write frequency (aka pwm frequency) by calling ```analogWriteFreq``` in ```setup```
- there is some interplay between analog write range and frequency: [info](https://arduino-pico.readthedocs.io/en/latest/analog.html)
- the potentiometer analog read resolution is currently 10-bits (so has range [0-1023]), which means we could simply use the same range for the pwm.  We just need to make sure that we don't choose a pwm frequency so high that we can't achieve that resolution

Note that bpm ctrl output pin is GP3 (pin # 3)

**Comment by cosparks** [comment]
This class can go in System folder

**Comment by LaPommeCosmique** [comment]
Documentation for the physical BPM component: https://www.notion.so/Off-Board-Components-0a6a960854d7498bbabc718105479ab2

**Comment by KevinZhiyuanDing** [comment]
I have made the BPM control class. 
The constructor takes the pin number for the BPM control output pin. 
I have added the pin number definition in ```settings.h```:

```
//BPM
#define BPM_CTRL_OUT        3
```

The pi pico outputs a PWM signal from the BPM_CTRL_OUT pin. The signal is augmented by the amplifier and doubled in amplitude, and then send to the BPM control module to control breaking power.

The BPM control class if included below. The pwm has a range of (0,1023) and analog frequency of  20kHz for now (i'm not sure if this frequency is suitable or not):
```
#include "HardwareInput.h"
#include "BpmControl.h"

#define ANALOG_MAX 1023
#define ANALOG_FREQ 20000

BpmControl::BpmControl (pin_size_t pinNum){
    _pinNum = pinNum;
}

void BpmControl::init (){
    pinMode(_pinNum, OUTPUT);
    analogWriteRange(ANALOG_MAX);
    analogWriteFreq(ANALOG_FREQ);
};

void BpmControl::setControlSignal (int32_t controlSignal){ 
    if (_active == true){
        if (controlSignal >= 0 && controlSignal <= 1023){
            analogWrite (_pinNum, controlSignal);
        }
    }
    else {
        analogWrite (_pinNum, 0);
    }
};

void BpmControl::setActive (bool active){
    _active = active;
    if (active == false) {
        analogWrite (_pinNum, 0);
    }
};
```
Its corresponding header file is:
```
#ifndef _BPM_CONTROL_H_
#define _BPM_CONTROL_H_
#include "settings.h"

class BpmControl {
    private:    
        int _pinNum;
        bool _active = false;
    public:
        BpmControl (pin_size_t pinNum);
        void init ();
        void setControlSignal (int32_t signalStrength);
        void setActive (bool state);
};

#endif
```
