### ISSUE TITLE
Adjust encoder sensitivity/speed

### ISSUE THREAD

**Issue by LaPommeCosmique** [supermileage/dynamometer-firmware#91]
Suggested by @TZlindra.

Right now the moving the encoder toggles through the options very quickly. For better user experience, it would better to have a lower encoder sensitivity to make it easier to navigate different options. Maybe we can add a "sensitivity" parameter in settings where the user can adjust the encoder sensitivity to their preferences.

Also, I think the direction of the encoder is flipped (going counterclockwise is forward, and clockwise is backward).

**Comment by cosparks** [comment]
> For better user experience, it would better to have a lower encoder sensitivity to make it easier to navigate different options

You shouldn't need to create a sensitivity param for the rotary encoder. It should simply be moving one selection forward/backward when rotating from one position to another. That is pretty standard for rotary encoder inputs. You might want to consider replacing it with one that emits fewer pulses per rotation, but honestly I think rotary encoders just take some time to get used to.

> Also, I think the direction of the encoder is flipped (going counterclockwise is forward, and clockwise is backward).

Clockwise should be down/right and counter-clockwise is up/left depending on the orientation of the UI elements. This is also standard behaviour.
